---
title: "p8105_hw2_xf2302"
output: github_document
date: "2025-09-30"
---
# Problem 1
```{r}
library(tidyverse)
```
# Clean pols-month.csv dataset
```{r}
pols <- 
  read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    month = month.name[month],
    president = if_else(prez_gop == 1, "gop", "dem")
  ) |> 
  select(-day, -prez_gop, -prez_dem)
```
# 2. Clean snp.csv dataset
```{r}
snp <- 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(
    month = as.integer(month),
    year = as.integer(year),
    year = if_else(year > 50, 1900 + year, 2000 + year),
    month = month.name[month]
  ) |> 
  select(year, month, close) |> 
  arrange(year, month)
```
# 3. Clean unemployment.csv
```{r}
unemployment <- 
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    year = as.integer(Year),
    month = month.name[match(month, month.abb)]
  ) |> 
  select(year, month, unemployment)
```