p8105_hw2_xf2302
================
2025-09-30

# Problem 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.1.4     ✔ readr     2.1.5
    ## ✔ forcats   1.0.0     ✔ stringr   1.5.1
    ## ✔ ggplot2   3.5.2     ✔ tibble    3.3.0
    ## ✔ lubridate 1.9.4     ✔ tidyr     1.3.1
    ## ✔ purrr     1.1.0     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

# Clean pols-month.csv dataset

``` r
pols <- 
  read_csv("data/pols-month.csv") |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    year = as.integer(year),
    month = as.integer(month),
    month = month.name[month],
    president = if_else(prez_gop == 1, "gop", "dem")
  ) |> 
  select(-day, -prez_gop, -prez_dem)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# 2. Clean snp.csv dataset

``` r
snp <- 
  read_csv("data/snp.csv") |> 
  separate(date, into = c("month", "day", "year"), sep = "/") |> 
  mutate(
    month = as.integer(month),
    year = as.integer(year),
    year = if_else(year < 100,            
                   if_else(year >= 50, 1900 + year, 2000 + year),
                   year),
    month = month.name[month]
  ) |> 
  select(year, month, close) |> 
  arrange(year, month)
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# 3. Clean unemployment.csv

``` r
unemployment <- 
  read_csv("data/unemployment.csv") |> 
  pivot_longer(
    Jan:Dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    year = as.integer(Year),
    month = month.name[match(month, month.abb)]
  ) |> 
  select(year, month, unemployment)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# 4. Merge datasets and inspect merged dataset

``` r
merged_data <- 
  pols |> 
  left_join(snp, by = c("year", "month")) |> 
  left_join(unemployment, by = c("year", "month"))
dim(merged_data)        
```

    ## [1] 822  11

``` r
range(merged_data$year) 
```

    ## [1] 1947 2015

``` r
head(merged_data)       
```

    ## # A tibble: 6 × 11
    ##    year month    gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##   <dbl> <chr>      <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ## 1  1947 January       23      51     253      23      45     198 dem          NA
    ## 2  1947 February      23      51     253      23      45     198 dem          NA
    ## 3  1947 March         23      51     253      23      45     198 dem          NA
    ## 4  1947 April         23      51     253      23      45     198 dem          NA
    ## 5  1947 May           23      51     253      23      45     198 dem          NA
    ## 6  1947 June          23      51     253      23      45     198 dem          NA
    ## # ℹ 1 more variable: unemployment <dbl>

The **FiveThirtyEight datasets** combine information on U.S. politics,
the stock market, and unemployment. The `pols-month.csv` dataset
contains monthly counts of national politicians (governors, senators,
and representatives) by political party, from 1947 to 2015.

The `snp.csv` dataset records monthly closing values of the S&P 500
index, ranging from 1950 to 2015. The `unemployment.csv` dataset
provides national unemployment rates, reported monthly from 1948 to
2015.

After cleaning and merging these datasets by year and month, the
resulting dataset has **822 rows** and **11 variables**, covering the
period **1947–2015**. Key variables include the counts of politicians by
party, the sitting president’s party, monthly unemployment rates, and
the S&P 500 closing values. Note that missing values occur where data
are not available (e.g., stock market values before 1950, unemployment
data in 1947).

# Problem 2

``` r
library(readxl)
library(dplyr)
library(janitor)
```

    ## 
    ## Attaching package: 'janitor'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     chisq.test, fisher.test

# Define a Cleaning Function

``` r
clean_trash <- function(sheet_name, wheel_name) {
  df <- read_excel(
    "data/202509 Trash Wheel Collection Data.xlsx",
    sheet = sheet_name,
    skip = 1
  ) |>
    clean_names() |> 
    filter(!is.na(dumpster)) |>          
    select(-starts_with("...")) |> 
    mutate(
      year = as.integer(year)   
    )
  
  if ("sports_balls" %in% colnames(df)) {
    df <- df |>
      mutate(sports_balls = as.integer(round(sports_balls, 0)))
  } else {
    df <- df |>
      mutate(sports_balls = NA_integer_)
  }
  df |>
    mutate(wheel = wheel_name)
}
```

# Clean Each Trash Wheel Dataset and combine Datasets

``` r
mr_trash   <- clean_trash("Mr. Trash Wheel", "Mr. Trash Wheel")
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
prof_trash <- clean_trash("Professor Trash Wheel", "Professor Trash Wheel")
gwynnda    <- clean_trash("Gwynns Falls Trash Wheel", "Gwynnda")
all_trash <- bind_rows(mr_trash, prof_trash, gwynnda)
```

# Compute Results

``` r
n_obs <- nrow(all_trash)
prof_total_weight <- sum(prof_trash$weight_tons, na.rm = TRUE)
gwynnda_cig_2022_06 <- gwynnda |>
  filter(year == 2022, month == "June") |>
  summarise(total_cig = sum(cigarette_butts, na.rm = TRUE)) |>
  pull(total_cig)
n_obs
```

    ## [1] 1188

``` r
prof_total_weight
```

    ## [1] 282.26

``` r
gwynnda_cig_2022_06
```

    ## [1] 18120

The combined Trash Wheel dataset contains 1188 observations.  
Professor Trash Wheel collected a total of 282.26 tons of trash.  
In June 2022, Gwynnda collected 18,120 cigarette butts. Key variables
include dumpster ID, collection date, total weight (in tons), counts of
plastic bottles, polystyrene, cigarette butts, and sports balls.

# Problem 3

library(readr) library(dplyr) library(tidyr) library(janitor)

# Load and clean Zip Codes and ZORI data

``` r
zips <- read_csv("data/Zip Codes.csv") %>% 
  clean_names()
```

    ## Rows: 322 Columns: 7
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (4): County, County Code, File Date, Neighborhood
    ## dbl (3): State FIPS, County FIPS, ZipCode
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
zori <- read_csv("data/Zip_zori_uc_sfrcondomfr_sm_month_NYC.csv") %>% 
  clean_names()
```

    ## Rows: 149 Columns: 125
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr   (6): RegionType, StateName, State, City, Metro, CountyName
    ## dbl (119): RegionID, SizeRank, RegionName, 2015-01-31, 2015-02-28, 2015-03-3...
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

# Tidy ZORI data

``` r
zori_tidy <- zori %>% 
  pivot_longer(
    cols = starts_with("x"),       
    names_to = "month",
    values_to = "rent_index"
  ) %>% 
  mutate(
    month = gsub("^x", "", month),                 
    month = as.Date(month, format = "%Y_%m_%d")    
  )
```

# Deduplicate ZIPs

``` r
zips_unique <- zips %>% distinct(zip_code, .keep_all = TRUE)
```

# Join ZORI + ZIP

``` r
zori_final <- zori_tidy %>%
  left_join(zips_unique, by = c("region_name" = "zip_code")) %>%
  arrange(region_name, month)
```

# Compute stats

``` r
n_obs <- nrow(zori_final)                                 
n_zip <- n_distinct(zori_final$region_name)               
n_neighborhood <- n_distinct(zori_final$neighborhood)     
```

# Find missing ZIPs

``` r
missing_zips <- setdiff(zips_unique$zip_code, zori$region_name)
```
